### ISSUE TITLE
Setting "value" on a <paper-input type="password"> causes "invalid" attribute to be ignored

### ISSUE THREAD

**Issue by jab** [PolymerElements/paper-input#238]
Please see http://jsbin.com/mopuja/edit?html,output for a minimal reproduction.

**Comment by notwaldorf** [comment]
I think you may have reused the same jsbin. I don't see any password inputs in that demo :)

**Comment by jab** [comment]
Sorry about that @notwaldorf, not sure how that happened. Should be fixed now at the original link in the description. If that somehow doesn't work, http://jsbin.com/mopuja/16/edit?html,output definitely should.

**Comment by jab** [comment]
I did some more testing and realized this occurs with other input types (not just password), and inferred what's really happening. Just updated the title to reflect this: "paper-input with `auto-validate` and an invalid initial `value` set do not get `invalid` set".

Here is a jsbin to demonstrate: http://jsbin.com/nuyula/edit?html,output

The first paper-input has `auto-validate`, `maxlength=8`, and `value="foo"`, which is not long enough, but isn't getting `invalid` set automatically.

I realized you can work around this by setting `pattern`. I did that in the second paper-input and you can see it is getting `invalid` set properly.

**Comment by jab** [comment]
(and by maxlength I meant minlength; updated previous comment)

**Comment by notwaldorf** [comment]
Hmm, there's definitely a bug there. Let me know if you're interested in debugging this and figuring out where it is :)

**Comment by admwx7** [comment]
After a bit of poking around and trying to circumvent this issue, looks like it is a case when value is an empty string, and clearing out value (setting explicitly to undefined when value hits '') does not fix it, maybe there's a stray dirty check somewhere?

I'll see if I can get some time to look into it directly at some point.
